version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: slack_meetup_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: app
    environment:
      PORT: 1323
    volumes:
      - .:/go/src/app
    ports:
      - "1323:1323"
    depends_on:
      - db
